export const ADD_KEG = 'ADD_KEG';
export const DELETE_KEG = 'DELETE_KEG';
export const TOGGLE_FORM = 'TOGGLE_FORM';
export const MAKE_SELECTED_TICKET = 'MAKE_SELECTED_TICKET';
export const REMOVE_SELECTED_TICKET = 'REMOVE_SELECTED_TICKET';